name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      ENV: ${{ secrets.ENV }}
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and report to Cypress Dashboard
        run: |
          npx cypress run --browser electron --record --key ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports/html
          publish_branch: report-page
